config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  resources :questions do
    resources :answers
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  validates :description,
    presence: true,
    length: { minimum: 50 }
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy

  default_scope { order('created_at DESC') }
  validates :title,
    presence: true,
    uniqueness: true,
    length: { minimum: 40 }

  validates :description,
    presence: true,
    length: { minimum: 150 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    # @answer = Answer.new(answer_params)
    # @answer.question = @question
    if @answer.save
      flash[:notice] = 'Answer added.'
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  protected
  def answer_params
    params.require(:answer).permit(:description)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:notice] = 'Question added.'
      redirect_to '/'
    else
      render :new
    end
  end

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    @answers = Answer.where(question_id: @question.id)
    render :show
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question, notice: "Question Successfully Updated!"
    else
      render :action => :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash[:notice] = 'Question deleted.'
    redirect_to root_path
  end

  protected
  def question_params
    params.require(:question).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/new.html.erb
<div class="row">
  <div class="large-12">

    <%- if @answer.errors.present? -%>
        <ul>
          <%- @answer.errors.full_messages.each do |error| -%>
            <li><%= error %></li>
          <%- end -%>
        </ul>
      </div>
    <%- end -%>
    <h4 class="question_title">Question:</h4>
    <h5 id="question_answer"><%= @question.title %></h5>


    <%= form_for [@question, @answer] do |f| %>
      <h4><%= f.label :answer, class: "question_title" %></h4>
      <%= f.text_area :description, class: "question_field" %>

      <%= f.submit "Submit Answer", class: 'button tiny'  %>
    <%- end -%>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Chau+Philomene+One' rel='stylesheet' type='text/css'>
</head>
<body>
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Rescue Mission Question Queue</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

<%= yield %>

<%= javascript_include_tag 'application' %>
<%= yield :extra_footer %>
</body>
</html>

app/views/questions/_form.html.erb
​<%= form_for(@question) do |f| %>

  <div class="field">
    <%= f.label "Question", class: "question_title" %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label "description", class: "question_title" %><br>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit "Update Question", class: "button tiny" %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<div class="row">
  <div class="large-12">

    <h3 class="question_title">Edit a question</h3>

    <%= render 'form' %>
    <%= link_to 'Delete', question_path, method: :delete, class: "button tiny" %>
    <%= link_to 'Back', questions_path, class: "button tiny" %>

  </div>
</div>

app/views/questions/index.html.erb
<div class="row">
  <div class="large-12">
    <h2 class="question_title">Questions:</h2>
      <table>
      <% @questions.each do |question| %>
      <tr>
        <td class="answer"><%= link_to question.title, question_path(question), class: "question_field" %></td>
      </tr>
      <% end %>
    </br>
    <%= link_to 'Submit A New Question', '/questions/new', class: 'button tiny' %>
  </div>
</div>
<img class="dragon" src="images/dragon.jpeg">

app/views/questions/new.html.erb
<%- if @question.errors.present? -%>
  <div class="large-12 alert-box alert" data-alert>
    <ul>
      <%- @question.errors.full_messages.each do |error| -%>
        <li><%= error %></li>
      <%- end -%>
    </ul>
  </div>
<%- end -%>

<div class="row">
  <div class="large-12">
    <%= form_for @question do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: "question_field" %>
      <p>
      <%= f.label :description %>
      <%= f.text_area :description, class: "question_field" %>
    </p>
      <%= f.submit "Add Question", class: 'button tiny' %>
    <%- end -%>
  </div>
</div>

app/views/questions/show.html.erb
<div class="row">
  <div class="large-12">

    <h3 class="question_title"><%= @question.title %></h3>
    <p><%= @question.description %></p>
    <%= link_to 'Edit', edit_question_path, class: 'button tiny'%>
    <%= link_to 'Delete', question_path, method: :delete, class: 'button tiny' %>
    <h4 class="question_title">Answers:</h4>
      <% @answers.each do |answer| %>
      <p class="answer">
        <%= answer.description %>
      </p>
      <% end %>

    <%= link_to 'Answer This Question', new_question_answer_path(@question), class: 'button tiny' %></br>

  </div>
</div>